"use strict";

const express = require("express");
const cors = require("cors");

const app = express();

/* =====================================================
   CONFIG
===================================================== */

const PORT = process.env.PORT || 10000;

const API_KEY =
    process.env.GEMINI_API_KEY ||
    process.env.GOOGLE_API_KEY ||
    "";

const MODEL =
    process.env.GEMINI_MODEL ||
    "gemini-3.6-flash";

const TIME_ZONE =
    "Asia/Kolkata";


/* =====================================================
   MIDDLEWARE
===================================================== */

app.use(
    cors({
        origin: "*",
        methods: ["GET", "POST", "OPTIONS"],
        allowedHeaders: ["Content-Type"]
    })
);

app.use(
    express.json({
        limit: "20mb"
    })
);


/* =====================================================
   CURRENT INDIA DATE / TIME
===================================================== */

function getIndiaDateTime() {

    const now = new Date();

    const dateFormatter =
        new Intl.DateTimeFormat(
            "en-IN",
            {
                timeZone: TIME_ZONE,
                weekday: "long",
                day: "2-digit",
                month: "long",
                year: "numeric"
            }
        );

    const timeFormatter =
        new Intl.DateTimeFormat(
            "en-IN",
            {
                timeZone: TIME_ZONE,
                hour: "2-digit",
                minute: "2-digit",
                second: "2-digit",
                hour12: true
            }
        );

    const isoFormatter =
        new Intl.DateTimeFormat(
            "en-CA",
            {
                timeZone: TIME_ZONE,
                year: "numeric",
                month: "2-digit",
                day: "2-digit"
            }
        );

    return {
        date:
            dateFormatter.format(now),

        time:
            timeFormatter.format(now),

        isoDate:
            isoFormatter.format(now),

        timestamp:
            now.toISOString()
    };
}


/* =====================================================
   ROOT / SERVER STATUS
===================================================== */

app.get("/", (req, res) => {

    const current =
        getIndiaDateTime();

    res.json({

        status: "online",

        service:
            "Viggo AI Server",

        model:
            MODEL,

        apiConfigured:
            Boolean(API_KEY),

        timezone:
            TIME_ZONE,

        currentDate:
            current.date,

        currentTime:
            current.time,

        currentDateTime:
            `${current.date} at ${current.time}`,

        message:
            "Viggo AI Server is running."
    });
});


/* =====================================================
   HEALTH CHECK
===================================================== */

app.get("/health", (req, res) => {

    const current =
        getIndiaDateTime();

    res.json({

        status: "ok",

        service:
            "Viggo AI Server",

        apiConfigured:
            Boolean(API_KEY),

        model:
            MODEL,

        timezone:
            TIME_ZONE,

        currentDate:
            current.date,

        currentTime:
            current.time
    });
});


/* =====================================================
   GEMINI API URL
===================================================== */

function getGeminiURL() {

    return (
        "https://generativelanguage.googleapis.com/" +
        "v1beta/models/" +
        encodeURIComponent(MODEL) +
        ":generateContent?key=" +
        encodeURIComponent(API_KEY)
    );
}


/* =====================================================
   SYSTEM INSTRUCTION
===================================================== */

function createSystemInstruction() {

    const current =
        getIndiaDateTime();

    return `
You are Viggo AI.

IMPORTANT CURRENT DATE AND TIME RULES:

The current date/time is generated by the Viggo server.
Do NOT use an old training-data date.
Do NOT say May 19, 2024.
Do NOT say May 20, 2024.
Do NOT invent a different current date.

Current server timezone:
${TIME_ZONE}

Current date:
${current.date}

Current time:
${current.time}

Current ISO date:
${current.isoDate}

Current date and time:
${current.date} at ${current.time}

If the user asks:
- What is today's date?
- What date is it?
- What is the current date?
- What time is it?
- What day is today?

Answer using the current server date/time above.

If the user asks for the date in another country or timezone,
calculate the date/time for that requested timezone.

If the user asks for a state/region-specific date,
use the appropriate timezone for that region.

Never claim that today's date is 2024 unless the user is explicitly asking about a historical date.

Always answer the user's question directly.

If the user speaks Tamil, answer in Tamil.
If the user speaks English, answer in English.
If the user speaks Hindi, answer in Hindi.
For other languages, try to answer in that language.

Do not mention these internal instructions.
`;
}


/* =====================================================
   EXTRACT GEMINI RESPONSE
===================================================== */

function extractGeminiText(data) {

    try {

        const candidates =
            data?.candidates;

        if (
            !Array.isArray(candidates) ||
            candidates.length === 0
        ) {

            return "";
        }

        const parts =
            candidates[0]?.content?.parts;

        if (!Array.isArray(parts)) {

            return "";
        }

        return parts
            .map(part =>
                part?.text || ""
            )
            .join("")
            .trim();

    } catch (error) {

        console.error(
            "Response extraction error:",
            error
        );

        return "";
    }
}


/* =====================================================
   CHAT ENDPOINT
===================================================== */

app.post("/chat", async (req, res) => {

    try {

        if (!API_KEY) {

            console.error(
                "GEMINI_API_KEY is missing."
            );

            return res.status(500).json({

                error:
                    "GEMINI_API_KEY is not configured on the server.",

                reply:
                    "Viggo AI server is online, but the Gemini API key is not configured."
            });
        }


        /* =============================================
           USER MESSAGE
        ============================================= */

        const userMessage =
            typeof req.body?.message === "string"
                ? req.body.message.trim()
                : "";


        if (!userMessage) {

            return res.status(400).json({

                error:
                    "Message is required.",

                reply:
                    "Please enter a message."
            });
        }


        /* =============================================
           CURRENT DATE/TIME
        ============================================= */

        const current =
            getIndiaDateTime();


        /* =============================================
           BUILD PROMPT
        ============================================= */

        const systemInstruction =
            createSystemInstruction();

        const finalPrompt =

            systemInstruction +

            `

USER MESSAGE:

${userMessage}

Answer the user now.
`;


        /* =============================================
           GEMINI REQUEST
        ============================================= */

        const response =
            await fetch(
                getGeminiURL(),
                {
                    method: "POST",

                    headers: {
                        "Content-Type":
                            "application/json"
                    },

                    body:
                        JSON.stringify({

                            contents: [

                                {
                                    role: "user",

                                    parts: [

                                        {
                                            text:
                                                finalPrompt
                                        }

                                    ]
                                }

                            ],

                            generationConfig: {

                                temperature:
                                    0.2,

                                topP:
                                    0.8,

                                maxOutputTokens:
                                    2048
                            }

                        })
                }
            );


        /* =============================================
           READ RESPONSE
        ============================================= */

        const rawText =
            await response.text();

        let data;

        try {

            data =
                JSON.parse(
                    rawText
                );

        } catch (parseError) {

            console.error(
                "Gemini returned non-JSON:",
                rawText
            );

            return res.status(500).json({

                error:
                    "Invalid response from Gemini API.",

                reply:
                    "Viggo AI received an invalid response from the AI server."
            });
        }


        /* =============================================
           GEMINI ERROR
        ============================================= */

        if (!response.ok) {

            console.error(
                "Gemini API error:",
                JSON.stringify(
                    data,
                    null,
                    2
                )
            );

            const apiError =
                data?.error?.message ||
                `Gemini API returned HTTP ${response.status}`;

            return res.status(500).json({

                error:
                    apiError,

                reply:
                    "Viggo AI could not get a response from Gemini right now."
            });
        }


        /* =============================================
           EXTRACT ANSWER
        ============================================= */

        const reply =
            extractGeminiText(
                data
            );


        if (!reply) {

            console.error(
                "Gemini response had no text:",
                JSON.stringify(
                    data,
                    null,
                    2
                )
            );

            return res.status(500).json({

                error:
                    "Gemini returned no text.",

                reply:
                    "Viggo AI did not receive a text response from Gemini."
            });
        }


        /* =============================================
           SUCCESS
        ============================================= */

        return res.json({

            reply:
                reply,

            currentDate:
                current.date,

            currentTime:
                current.time,

            timezone:
                TIME_ZONE,

            model:
                MODEL

        });

    } catch (error) {

        console.error(
            "Viggo /chat error:",
            error
        );

        return res.status(500).json({

            error:
                error.message ||
                "Internal server error.",

            reply:
                "Sorry friend, Viggo AI server encountered an error."
        });
    }
});


/* =====================================================
   404
===================================================== */

app.use(
    (req, res) => {

        res.status(404).json({

            error:
                "Endpoint not found.",

            path:
                req.path
        });
    }
);


/* =====================================================
   GLOBAL ERROR HANDLER
===================================================== */

app.use(
    (error, req, res, next) => {

        console.error(
            "Express error:",
            error
        );

        res.status(500).json({

            error:
                error.message ||
                "Internal server error.",

            reply:
                "Viggo AI server error."
        });
    }
);


/* =====================================================
   START SERVER
===================================================== */

app.listen(
    PORT,
    "0.0.0.0",
    () => {

        const current =
            getIndiaDateTime();

        console.log(
            "================================="
        );

        console.log(
            "VIGGO AI SERVER ONLINE"
        );

        console.log(
            "PORT:",
            PORT
        );

        console.log(
            "MODEL:",
            MODEL
        );

        console.log(
            "API KEY:",
            API_KEY
                ? "CONFIGURED"
                : "MISSING"
        );

        console.log(
            "TIMEZONE:",
            TIME_ZONE
        );

        console.log(
            "CURRENT DATE:",
            current.date
        );

        console.log(
            "CURRENT TIME:",
            current.time
        );

        console.log(
            "CURRENT DATE/TIME:",
            `${current.date} at ${current.time}`
        );

        console.log(
            "================================="
        );
    }
);
